name: Docker image CD

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.DOCKER_REPOSITORY || 'joarley/ghostfolio' }}
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/ghostfolio:latest
            ghcr.io/${{ github.repository_owner }}/ghostfolio:${{ github.ref_name }}
          labels: ${{ steps.meta.output.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
