name: Extract locales

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  extract_locales:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 24 or superior
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          check-latest: true
          
      #- name: Update npm to v24
      #  run: npm install -g npm@24

      - name: Install dependencies
        run: npm ci

      - name: Extract locales
        run: npm run extract-locales

      - name: Check changes
        id: verify-changed-files
        uses: tj-actions/verify-changed-files@v20

      - name: Create pull request
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          branch: 'feature/update-locales'
          commit-message: 'Update locales'
          delete-branch: true
          title: 'Feature/update locales'
          token: ${{ secrets.GITHUB_TOKEN }}
